BLOGS_COLLECTION = 'blogs'
POSTS_COLLECTION = 'posts'
USERS_COLLECTION = 'users'
DBNAME = 'fullstack'

AUTHOR = 'author'
TITLE = 'title'
DESCRIPTION = 'description'
DATE = 'date'
BLOG_ID = 'blog_id'
POST_ID = 'post_id'
USER_ID = 'user_id'
AUTHOR_ID = 'author_id'
SELF_ID = '_id'
CONTENT = 'content'
EMAIL = 'email'
USERNAME = 'username'
PASSWORD = 'password'
